### ISSUE TITLE
Bot not able to be added

### ISSUE THREAD

**Issue by peepo5** [SmellyModder/Pet-Pet#2]
![image](https://user-images.githubusercontent.com/72892531/136196458-84b984ce-824f-42f5-bba4-2abd72cb3e9d.png)

**Comment by MegaMoist22** [comment]
I have the same issue 😭

**Comment by SmellyModder** [comment]
This is good and bad news.
The bot has reached the maximum amount of servers a bot can be in without being verified, meaning the bot is popular.
I'll look into fixing this.

**Comment by SmellyModder** [comment]
Moving this issue to #3
