### ISSUE TITLE
Bot cannot get added because it's not verified and has reached the 100 server limit

### ISSUE THREAD

**Issue by ChuckieFinster12** [SmellyModder/Pet-Pet#3]
hello, could you fix the error of putting the bot to a server .....

**Comment by SmellyModder** [comment]
Is your issue the same as #2?

**Comment by ChuckieFinster12** [comment]
yes, it is because you put it in a way that it could only be added in 100 server, could you deactivate it?

**Comment by ChuckieFinster12** [comment]
you need fix as fast as possible...

**Comment by SmellyModder** [comment]
I haven't verified the bot yet because the verification form was buggy, but I will try again today!

**Comment by SmellyModder** [comment]
I've sent out the verification request to Discord.

**Comment by ChuckieFinster12** [comment]
ok

**Comment by SmellyModder** [comment]
Discord has accepted the verification request. The bot should be able to get added to more servers now, but it may take some time to update.

**Comment by ChuckieFinster12** [comment]
ok thanks

**Comment by ChuckieFinster12** [comment]
i try add and say the same, you need change the link

**Comment by SmellyModder** [comment]
Sorry, I can't do it anymore.
They've denied my request:
> "Unfortunately, I am denying your Guild Members & Message Content Privileged Intent request. This is because we are only providing access to our privileged gateway intents to power unique, compelling, user-facing functionality, and we do not believe your use-case meet this criteria."

My bot is just not cool enough for Discord. Very nice of them... nothing I can do about this really.
Honestly, developing with Discord API is such a pain in the ass.

**Comment by SmellyModder** [comment]
The bot can now be added to more servers! 🎉
